import type * as NodeCrypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, test, vi } from "vitest";
import { runBridgeHost } from "../../src/cli/bridge/host.js";
import { createRemoteServer } from "../../src/remote/server.js";
import { CAN_LISTEN_LOCALHOST } from "./serverTestBuilders.js";

const cryptoHarness = vi.hoisted(() => {
  const bytes = Array.from({ length: 32 }, (_, index) => index);
  return {
    bytes,
    randomBytes: vi.fn((size: number) => {
      if (size !== 32) throw new Error(`expected a 32-byte credential request, received ${size}`);
      return Buffer.from(bytes);
    }),
  };
});

vi.mock("node:crypto", async (importOriginal) => {
  const actual = await importOriginal<typeof NodeCrypto>();
  return { ...actual, randomBytes: cryptoHarness.randomBytes as typeof actual.randomBytes };
});

const EXPECTED_TOKEN = Buffer.from(cryptoHarness.bytes).toString("hex");

describe("remote credential generation", () => {
  test("bridge host encodes the exact 32 generated bytes as lowercase hex", async () => {
    const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "oracle-bridge-credential-bytes-"));
    const artifactPath = path.join(tempDir, "bridge-connection.json");
    const log = vi.spyOn(console, "log").mockImplementation(() => undefined);
    let servedToken: string | undefined;
    cryptoHarness.randomBytes.mockClear();
    try {
      await runBridgeHost(
        { token: "auto", writeConnection: artifactPath },
        {
          serveRemote: async (options, lifecycle) => {
            const token = options?.token;
            if (!token) throw new Error("missing generated bridge credential");
            servedToken = token;
            await lifecycle?.onReady?.({ port: 9473, token });
          },
        },
      );
      const artifact = JSON.parse(await fs.readFile(artifactPath, "utf8")) as {
        remoteToken?: string;
      };

      expect(cryptoHarness.randomBytes).toHaveBeenCalledOnce();
      expect(cryptoHarness.randomBytes).toHaveBeenCalledWith(32);
      expect(servedToken).toBe(EXPECTED_TOKEN);
      expect(artifact.remoteToken).toBe(EXPECTED_TOKEN);
      expect(EXPECTED_TOKEN).toMatch(/^[0-9a-f]{64}$/u);
    } finally {
      log.mockRestore();
      await fs.rm(tempDir, { recursive: true, force: true });
    }
  });

  test.skipIf(!CAN_LISTEN_LOCALHOST)(
    "remote server encodes the exact 32 generated bytes as lowercase hex",
    async () => {
      const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "oracle-server-credential-bytes-"));
      await fs.writeFile(
        path.join(tempDir, ".remote-transaction-integrity.key"),
        Buffer.alloc(32, 0xa5),
        { mode: 0o600 },
      );
      if (process.platform !== "win32") {
        await fs.chmod(path.join(tempDir, ".remote-transaction-integrity.key"), 0o600);
      }
      cryptoHarness.randomBytes.mockClear();
      const server = await createRemoteServer(
        { host: "127.0.0.1", port: 0, logger: () => undefined },
        { transactionStoreDir: path.join(tempDir, "transactions") },
      );
      try {
        expect(cryptoHarness.randomBytes).toHaveBeenCalledOnce();
        expect(cryptoHarness.randomBytes).toHaveBeenCalledWith(32);
        expect(server.token).toBe(EXPECTED_TOKEN);
        expect(server.token).toMatch(/^[0-9a-f]{64}$/u);
      } finally {
        await server.close();
        await fs.rm(tempDir, { recursive: true, force: true });
      }
    },
  );
});
